In [9]:
"""Do operator overriding in Python for addition, substraction, multiplication, division, less than 
and greater than."""
import math
 
class Circle:
 
    def __init__(self, radius):
        self.radius = radius
 
    def get_result(self):
        return self.radius
 
    def area(self):
        return math.pi * self.radius ** 2
 
    def __add__(self, another_circle):
        return Circle(self.radius + another_circle.radius)
 
    def __sub__(self, another_circle):
        return Circle(self.radius - another_circle.radius)
 
    def __mul__(self, another_circle):
        return Circle(self.radius * another_circle.radius)
 
    def __gt__(self, another_circle):
        return Circle(self.radius > another_circle.radius)
 
    def __lt__(self, another_circle):
        return Circle(self.radius < another_circle.radius)
 
    def __ge__(self, another_circle):
        return Circle(self.radius >= another_circle.radius)
 
    def __le__(self, another_circle):
        return Circle(self.radius <= another_circle.radius)
 
    def __eq__(self, another_circle):
        return Circle(self.radius == another_circle.radius)
 
    def __ne__(self, another_circle):
        return Circle(self.radius != another_circle.radius)
 
 
c1 = Circle(10)
print(c1.get_result())
print(c1.area())
 
c2 = Circle(15)
print(c2.get_result())
print(c1.area())
 
c3 = c1 + c2
print(c3.get_result())
 
c3 = c2 - c1
print(c3.get_result())
 
c4 = c1 * c2
print(c4.get_result())
 
c5 = c1 < c2
print(c5.get_result())
 
c5 = c2 < c1
print(c5.get_result())

10
314.1592653589793
15
314.1592653589793
25
5
150
True
False


In [10]:
"""Exhibit single, multiple, multilevel,hierarchical and hybrid inheritence in Python."""
#SINGLE INHERITANCE
class Animal:  
    def speak(self):  
        print("Animal Speaking")   
class Dog(Animal):  
    def bark(self):  
        print("dog barking")  
d = Dog()  
d.bark()  
d.speak()

dog barking
Animal Speaking


In [11]:
#MULTILEVEL INHERITANCE
class Animal:  
    def speak(self):  
        print("Animal Speaking")  
class Dog(Animal):  
    def bark(self):  
        print("dog barking")  
class DogChild(Dog):  
    def eat(self):  
        print("Eating bread...")  
d = DogChild()  
d.bark()  
d.speak()  
d.eat()

dog barking
Animal Speaking
Eating bread...


In [12]:
#MULTIPLE INHERITANCE
class Calculation1:  
    def Summation(self,a,b):  
        return a+b  
class Calculation2:  
    def Multiplication(self,a,b):  
        return a*b  
class Derived(Calculation1,Calculation2):  
    def Divide(self,a,b):  
        return a/b  
d = Derived()  
print(d.Summation(10,20))  
print(d.Multiplication(10,20))  
print(d.Divide(10,20))

30
200
0.5


In [13]:
#HIERARCHIAL INHERITANCE
class Animal:  
    def speak(self):  
        print("Animal Speaking")  
class Dog(Animal):  
    def bark(self):  
        print("Barking!")  
class Cat(Animal):  
    def sound(self):  
        print("Meow!!")  
d = Dog()  
d.bark()  
d.speak()  

c = Cat()
c.sound()
c.speak()

Barking!
Animal Speaking
Meow!!
Animal Speaking


In [14]:
"""Python Program to Display the multiplication table."""
def mul(x):
  #base case
  if x==0:
    return
  r=1
  r=r*7*x
  print(x,"* 7 =",r)

  return mul(x-1)

mul(10)

10 * 7 = 70
9 * 7 = 63
8 * 7 = 56
7 * 7 = 49
6 * 7 = 42
5 * 7 = 35
4 * 7 = 28
3 * 7 = 21
2 * 7 = 14
1 * 7 = 7


In [15]:
"""Write a Python program to check leap year."""

year=int(input("Enter the year to check:"))

if year%4==0:
  print(f"{year} is a leap year.")
else:
  print(f"{year} is not a leap year.")

Enter the year to check:2016
2016 is a leap year.


In [16]:
"""Write a Python program to count the number of each vowels."""
def vowel_count(string):
  vowels = ['a', 'e', 'i', 'o', 'u']
  return len([i for i in string if i in vowels])

vowel_count("An apple a day keeps the doctor away")

11

In [17]:
"""Write a Python program to multiply two matrices."""

import numpy as np

A = [[12, 7, 3], 
    [4, 5, 6], 
    [7, 8, 9]] 
  

B = [[5, 8, 1, 2], 
    [6, 7, 3, 0], 
    [4, 5, 9, 1]] 
  
  
result= [[0,0,0,0], 
        [0,0,0,0], 
        [0,0,0,0]] 

result=np.dot(A,B)

print(result)

[[114 160  60  27]
 [ 74  97  73  14]
 [119 157 112  23]]
